name: Manage Contribution Board - Hourly
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  manage_project_board:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python 3.7
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.7"
      - name: Get project manager
        run: |
          pip install --upgrade pip
          pip install github-automation==0.2.3
      - name: Manage project
        run: |
          github-automation manage -c .github/project_conf/contributions.ini
        env:
          GITHUB_TOKEN: ${{ secrets.CONTENTBOT_GH_ADMIN_TOKEN }}
