name: Run Legacy Validate on Contributions
on:
  pull_request_target:
    branches:
      - contrib/**

jobs:
  legacy_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec # v9
      - name: Install Python Dependencies
        run: poetry install --with github-actions
      - name: Run legacy validate step
        run: poetry run demisto-sdk validate -g --post-commit --graph --skip-pack-dependencies --run-old-validate --skip-new-validate
